# @format

version: "1.0"

services:
  app:
    image: go_backend
    build:
      context: .
      args:
        PORT: ${PORT:-5000} # Default value if PORT is not provided
        DB_RENDER_URI: ${DB_RENDER_URI} # Ensure DB_RENDER_URI is passed or use a fallback
    environment:
      - PORT=${PORT}
      - DB_RENDER_URI=${DB_RENDER_URI}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .env:/app/.env # Optional .env file for environment variables

