# @format

version: "3.8"

services:
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-backend
    environment:
      - DB_URI=${DB_URI} # Use DB_URI from the .env file
      - PORT=${PORT} # Use PORT from the .env file
    ports:
      - "5000:5000" # Expose Go backend on port 5000
    networks:
      - go-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf # Correct mount for the Nginx config file
      - ./nginx/certificate:/etc/nginx/certificate # Mount certificate folder for SSL
    ports:
      - "80:80" # Expose HTTP port
      - "443:443" # Expose HTTPS port for SSL
    depends_on:
      - go-backend # Ensure Go backend starts before Nginx
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
